services:
  database:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - tj-networks

      
  backend-api:
    image: rfauzi/tj-api:latest
    depends_on:
      - database
    restart: unless-stopped
    ports:
      - "3001:443"
    env_file:
      - .env
    networks:
      - tj-networks

networks:
  tj-networks:
    driver: bridge